Repository project-cosmo-sns/cosmos, pull requests merged in 2024-05, with the labels that each got.

#67 [Feature] react-md-editor 연결 및 커스텀
  next.config.mjs
  package-lock.json
  package.json
  src/components/Common/IconCollection/index.tsx
  src/components/Post/MarkdownEditor/customPreviewButton.module.scss
  src/components/Post/MarkdownEditor/customPreviewButton.tsx
  src/components/Post/MarkdownEditor/customTool.tsx
  src/components/Post/MarkdownEditor/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/pages/_app.page.tsx
  src/styles/globals.scss
Labels: ✨ feat

#66 Feature/profile page 프로필 페이지 디자인 적용
  package-lock.json
  package.json
  public/images/X.svg
  public/images/setting.svg
  src/components/Common/ClassBadge/ClassBadge.module.scss
  src/components/Common/ClassBadge/index.tsx
  src/components/Common/ImageInput/index.tsx
  src/components/Common/ScrapList/index.tsx
  src/components/Profile/ProfileEditModal/ProfileEditModal.module.scss
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/index.tsx
  src/pages/profile/MemberDataContainer.module.scss
  src/pages/profile/index.page.tsx
  src/pages/profile/mockData.ts
  src/styles/_variables.scss
Labels: 💄design

#69 [Design] 컬러 변경 적용
  package-lock.json
  public/images/profile.svg
  src/components/Common/AuthorProfile/AuthorProfile.module.scss
  src/components/Common/AuthorProfile/index.tsx
  src/components/Common/CommentCard/CommentCard.module.scss
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Post/CategoryFlag/CategoryFlag.module.scss
  src/components/Post/CategoryFlag/index.tsx
  src/components/Post/CategoryList/index.tsx
  src/components/Post/HashTag/HashTagInput.module.scss
  src/components/Post/PostContent/PostContent.module.scss
  src/components/Post/PostEditor/PostEditor.module.scss
  src/components/Post/PostEditor/index.tsx
  src/components/Post/PostList/PostList.module.scss
  src/components/Post/PostList/index.tsx
  src/components/Post/PostPreview/PostPreview.module.scss
  src/components/Post/PostPreview/index.tsx
  src/pages/post/[postId]/PostDetail.module.scss
  src/pages/profile/index.page.tsx
  src/pages/write/PostWritePage.module.scss
  src/styles/Home.module.scss
  src/styles/_mixins.scss
Labels: 💄design

#71 [Feat] feed 미리보기 이미지 Ui & reactionContainer emoji ui & 피드 css 수정
  src/components/Common/EmojiBundle/EmojiBundle.module.scss
  src/components/Common/EmojiBundle/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/ReactionContainer/index.tsx
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedCardList/mockData.ts
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/FeedList.module.scss
  src/components/Feed/FeedList/index.tsx
  src/components/Feed/FeedList/mockData.ts
  src/components/Post/PostPreview/index.tsx
  src/pages/index.page.tsx
  src/pages/profile/index.page.tsx
Labels: 💄design, ✨ feat

#72 [feat] 알림, 검색 디자인 적용 / PopOver createPotal 적용
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/Buttons/ToggleButton/ToggleButton.module.scss
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/ContentContainer/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/Notification/Notification.module.scss
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/PopOverBox/index.tsx
  src/components/Common/SearchInput/SearchInput.module.scss
  src/components/Common/SearchInput/index.tsx
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
  src/components/Common/TodayQuestion/index.tsx
  src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss
  src/pages/_app.page.tsx
  src/utils/ModalScroll.ts
Labels: 💄design, ✨ feat

#73 [Feature] 해시태그 작성 시 검색 기능 추가 및 axios 요청 함수 추가
  package-lock.json
  package.json
  src/api/axios.ts
  src/api/fetchData.ts
  src/components/Post/HashTag/HashTagInput.module.scss
  src/components/Post/HashTag/HashTagInput.tsx
  src/utils/QueryProvider.tsx
Labels: ✨ feat

#80 [feat] 컬러 export 파일 추가, 아이콘 기본 색상 변경, 이모지 svg 별도 분리
  src/components/Common/EmojiCollection/EmojiCheckIcon.tsx
  src/components/Common/EmojiCollection/EmojiHeartIcon.tsx
  src/components/Common/EmojiCollection/EmojiLaughIcon.tsx
  src/components/Common/EmojiCollection/EmojiMeIcon.tsx
  src/components/Common/EmojiCollection/EmojiSadIcon.tsx
  src/components/Common/EmojiCollection/EmojiThumbsUpIcon.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ReactionContainer/index.tsx
  src/styles/_variables.scss
  src/styles/export.module.scss
Labels: 💄design, ✨ feat

#84 [Feature] 피드 관련 데이터 요청 기능 구현
  public/images/X.svg
  public/images/add.svg
  public/images/addImage.svg
  public/images/back.svg
  public/images/bell.svg
  public/images/camera.svg
  public/images/check.svg
  public/images/close.svg
  public/images/comment.svg
  public/images/delete.svg
  public/images/doubleLeft.svg
  public/images/doubleRight.svg
  public/images/down.svg
  public/images/edit.svg
  public/images/emoji.svg
  public/images/eye.svg
  public/images/followed.svg
  public/images/following.svg
  public/images/glass.svg
  public/images/home.svg
  public/images/kebab.svg
  public/images/left.svg
  public/images/like.svg
  public/images/link.svg
  public/images/purple.svg
  public/images/right.svg
  public/images/setting.svg
  public/images/share.svg
  public/images/up.svg
  public/images/user.svg
  src/components/Common/AuthorProfile/index.tsx
  src/components/Common/Badge/TermBadge/index.tsx
  src/components/Common/CommentCard/index.tsx
  src/components/Common/CommentInput/api.ts
  src/components/Common/CommentInput/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Feed/.gitkeep
  src/components/Feed/CreateFeed/api.ts
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/CreateFeed/type.ts
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/api.ts
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/api.ts
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/api.ts
  src/components/Feed/FeedList/index.tsx
  src/components/Feed/FeedList/mockData.ts
  src/components/Feed/types.ts
  src/pages/index.page.tsx
Labels: ✨ feat

#81 [fix] 팝오버 UI 위치 틀어짐 수정
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/Layout/Layout.module.scss
  src/components/Common/Layout/Notification/Notification.module.scss
  src/components/Common/Layout/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/PopOverBox/index.tsx
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
  src/pages/_app.page.tsx
Labels: 🐛 bug, 💄design

#85 [Feature] 프로필 페이지 피드 목록 불러오기
  .gitignore
  src/components/Common/CommentCard/api.ts
  src/components/Feed/FeedCard/api.ts
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/pages/profile/index.page.tsx
Labels: ✨ feat

#86 [Feature] 포스트 카드 디자인 변경 및 헤더 스크롤 방향에 따라 내려오도록 수정
  .eslintrc.json
  src/components/Common/CommentCard/index.tsx
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/ContentContainer/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Post/CategoryFlag/index.tsx
  src/components/Post/CategoryList/index.tsx
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/HashTag/index.tsx
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/components/Post/PostList/PostList.module.scss
  src/components/Post/PostList/index.tsx
  src/components/Post/PostPreview/PostPreview.module.scss
  src/components/Post/PostPreview/index.tsx
  src/components/Post/types.ts
  src/components/Profile/AuthForm/index.tsx
  src/components/Search/SearchList/index.tsx
  src/constants/categoryList.ts
  src/constants/generationRegex.ts
  src/hooks/useScrollDirection.tsx
  src/pages/index.page.tsx
  src/pages/post/[postId]/mockData.ts
  src/styles/globals.scss
  src/utils/getElaspedTime.ts
  src/utils/scrollToTop.ts
Labels: 💄design, ✨ feat

#91 [Feature] 포스트 작성/수정/삭제 및 상세, 목록 초기 데이터 불러오기
  src/api/fetchData.ts
  src/components/Common/Buttons/SortDropdown/index.tsx
  src/components/Common/ContentContainer/index.tsx
  src/components/Post/CategoryList/index.tsx
  src/components/Post/HashTag/HashTagInput.module.scss
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/HashTag/HashTagRecommend.tsx
  src/components/Post/HashTag/HashTagRecommendProps.module.scss
  src/components/Post/HashTag/index.tsx
  src/components/Post/Markdown/CodeBlock.tsx
  src/components/Post/PostComment/index.tsx
  src/components/Post/PostContent/PostContent.module.scss
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/Post/PostPreview/index.tsx
  src/components/Post/types.ts
  src/constants/hashTagCode.ts
  src/constants/sortType.ts
  src/pages/index.page.tsx
  src/pages/post/[postId]/index.page.tsx
  src/pages/post/[postId]/mockData.ts
  src/pages/write/index.page.tsx
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/globals.scss
  src/utils/QueryProvider.tsx
  src/utils/getElaspedTime.ts
Labels: ✨ feat

#92 [feat] 사용자 검색 화면 api 추가
  src/components/Search/FollowButton/FollowButton.module.scss
  src/components/Search/FollowButton/FollowButtonType.ts
  src/components/Search/FollowButton/index.tsx
  src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss
  src/components/Search/SearchAuthorProfile/index.tsx
  src/components/Search/SearchAuthorProfileList/SearchAuthorProfileList.module.scss
  src/components/Search/SearchAuthorProfileList/index.tsx
  src/components/Search/SearchList/index.tsx
  src/components/Search/type.ts
  src/pages/search/index.page.tsx
Labels: ✨ feat

#93 [feat] 알림 api 적용
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/Layout/Notification/type.ts
  src/components/Search/SearchAuthorProfile/index.tsx
Labels: ✨ feat

#94 [feat] 알림 피드인경우 모달 오픈 추가
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
Labels: ✨ feat

#99 [Feature] 포스트 이모지 목록 렌더링 및 추가/삭제 요청
  public/images/checkEmoji.svg
  public/images/heartEmoji.svg
  public/images/laughEmoji.svg
  public/images/meEmoji.svg
  public/images/sadEmoji.svg
  public/images/thumbsupEmoji.svg
  src/@types/type.ts
  src/api/fetchInitialFeed.ts
  src/api/fetchInitialPost.ts
  src/components/Common/EmojiBundle/EmojiBundle.module.scss
  src/components/Common/EmojiBundle/EmojiPreviewBundle.module.scss
  src/components/Common/EmojiBundle/EmojiPreviewBundle.tsx
  src/components/Common/EmojiBundle/index.tsx
  src/components/Common/EmojiButton/EmojiButton.module.scss
  src/components/Common/EmojiButton/index.tsx
  src/components/Common/EmojiCollection/EmojiCheckIcon.tsx
  src/components/Common/EmojiCollection/EmojiHeartIcon.tsx
  src/components/Common/EmojiCollection/EmojiLaughIcon.tsx
  src/components/Common/EmojiCollection/EmojiMeIcon.tsx
  src/components/Common/EmojiCollection/EmojiSadIcon.tsx
  src/components/Common/EmojiCollection/EmojiThumbsUpIcon.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/ReactionContainer/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/components/Post/HashTag/HashTagInput.module.scss
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/HashTag/HashTagRecommend.tsx
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/Post/PostPreview/index.tsx
  src/components/Post/types.ts
  src/components/Search/SearchPriview/index.tsx
  src/constants/.gitkeep
  src/constants/EmojiCode.ts
  src/hooks/.gitkeep
  src/hooks/useSendEmojiRequest.ts
  src/pages/index.page.tsx
  src/pages/profile/index.page.tsx
  src/styles/_mixins.scss
Labels: ✨ feat

#102 [Feature] feed api 댓글 수정, 삭제, 좋아요, 좋아요 취소 api 연결
  src/@types/type.ts
  src/components/Common/AuthorProfile/index.tsx
  src/components/Common/Buttons/DefaultButton/index.tsx
  src/components/Common/CommentCard/EditComment.tsx
  src/components/Common/CommentCard/api.ts
  src/components/Common/CommentCard/index.tsx
  src/components/Common/CommentInput/api.ts
  src/components/Common/CommentInput/index.tsx
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/Input/Input.module.scss
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/api.ts
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/components/Feed/types.ts
  src/components/Post/PostComment/index.tsx
  src/components/Profile/FollowList/Follow/index.tsx
  src/components/Search/AuthorProfile/index.tsx
  src/components/Search/SearchAuthorProfile/index.tsx
Labels: 🐛 bug, ♻️refactor, ✨ feat

#101 [Fix] 서치-팔로우 버튼 빌드 해결
  package-lock.json
  src/components/Search/FollowButton/FollowButton.module.scss
  src/components/Search/FollowButton/FollowButtonType.ts
  src/components/Search/FollowButton/index.tsx
  src/components/Search/SearchAuthorProfile/index.tsx
Labels: 🐛 bug

#109 [Feat] 댓글 요청 커스텀훅 제작
  src/components/Common/CommentCard/index.tsx
  src/components/Common/CommentInput/api.ts
  src/components/Feed/FeedCard/api.ts
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/api.ts
  src/components/Feed/FeedDetails/index.tsx
  src/hooks/useCommentRequest.ts
Labels: 🐛 bug, ♻️refactor, ✨ feat

#107 [feat] 툴킷 세팅, 검색어 key값 전역화
  package-lock.json
  package.json
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/SearchInput/index.tsx
  src/components/Search/SearchAuthorProfile/index.tsx
  src/pages/_app.page.tsx
  src/pages/search/index.page.tsx
  src/redux/.gitkeep
  src/redux/searchSlice.ts
  src/redux/store.ts
Labels: ✨ feat

#110 [Feat] 검색 결과 컴포넌트 교체, 팔로우/언팔로우 로직 추가
  src/components/Common/Buttons/FollowButton/FollowButtonType.ts
  src/components/Post/PostList/index.tsx
  src/components/Post/PostPreview/index.tsx
  src/components/Search/AuthorProfile/AuthorProfile.module.scss
  src/components/Search/AuthorProfile/index.tsx
  src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss
  src/components/Search/SearchAuthorProfile/index.tsx
  src/components/Search/SearchAuthorProfileList/SearchAuthorProfileList.module.scss
  src/components/Search/SearchList/SearchList.module.scss
  src/components/Search/SearchList/index.tsx
  src/components/Search/SearchPriview/SearchPriview.module.scss
  src/components/Search/SearchPriview/index.tsx
  src/hooks/useFollowClick.ts
Labels: ✨ feat

#113 [Feat] 프로필 수정, 마이페이지
  src/@types/type.ts
  src/components/Common/Buttons/DefaultButton/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/Profile/MyFeedList/api.ts
  src/components/Profile/MyFeedList/index.tsx
  src/components/Profile/MyPostList/api.ts
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/ProfileEditModal/getImageUploadUrl.ts
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileEditModal/uploadImageToS3.ts
  src/components/Profile/ProfileHeader/index.tsx
  src/pages/profile/api.ts
  src/pages/profile/index.page.tsx
Labels: ✨ feat

#114 [Feature] 포스트 댓글 작성 및 초기 데이터 10개, 삭제 모달 생성
  src/components/Common/DeleteModal/DeleteModal.module.scss
  src/components/Common/DeleteModal/index.tsx
  src/components/Post/PostComment/PostComment.module.scss
  src/components/Post/PostComment/index.tsx
  src/components/Post/PostContent/PostContent.module.scss
  src/components/Post/PostContent/index.tsx
  src/styles/_variables.scss
Labels: ✨ feat

#115 [Feature] 포스트 댓글 목록
  src/api/Follow.ts
  src/components/Feed/types.ts
  src/components/Post/PostComment/index.tsx
  src/components/Post/types.ts
  src/components/Profile/FollowList/index.tsx
  src/hooks/useInfiniteScroll.ts
Labels: ✨ feat

#116 [ Feat] 피드 무한 스크롤 구현
  src/components/Common/CommentCard/index.tsx
  src/components/Common/WriterProfile/index.tsx
  src/components/Feed/FeedCard/api.ts
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/FeedList.module.scss
  src/components/Feed/FeedList/index.tsx
  src/components/Feed/types.ts
  src/components/Profile/MyFeedList/index.tsx
  src/hooks/useInfiniteScroll.ts
Labels: 🐛 bug, ♻️refactor, ✨ feat

#117 [Feature] 포스트 이미지 업로드
  package-lock.json
  package.json
  src/components/Common/ImageInput/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/ReactionContainer/index.tsx
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/MarkdownEditor/MarkdownEditor.module.scss
  src/components/Post/MarkdownEditor/getUploadImageButton.tsx
  src/components/Post/MarkdownEditor/handleUploadImage.ts
  src/components/Post/MarkdownEditor/index.tsx
  src/components/Profile/MyPostList/api.ts
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Search/type.ts
Labels: ✨ feat

#120 [Feat] 프로필 페이지 오류 해결, 팔로우 버튼 수정
  src/components/Common/Buttons/FollowButton/FollowButton.module.scss
  src/components/Common/Buttons/FollowButton/index.tsx
  src/components/Profile/ProfileEditModal/ProfileEditModal.module.scss
  src/components/Profile/ProfileEditModal/getImageUploadUrl.ts
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileEditModal/uploadImageToS3.ts
  src/components/Profile/ProfileHeader/index.tsx
  src/hooks/useFollowClick.ts
  src/pages/profile/index.page.tsx
Labels: 🐛 bug, ✨ feat

#122 [Feature] 포스트 목록 무한스크롤 및 카테고리, 정렬기준에 따른 데이터 불러오기, 댓글 구분선 및 포스트 수정/삭제 버튼 등 UI 조정
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/EmojiBundle/EmojiPreviewBundle.tsx
  src/components/Common/EmojiButton/EmojiButton.module.scss
  src/components/Common/EmojiButton/index.tsx
  src/components/Common/WriterProfile/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Post/CategoryFlag/index.tsx
  src/components/Post/CategoryList/index.tsx
  src/components/Post/PostComment/PostComment.module.scss
  src/components/Post/PostComment/index.tsx
  src/components/Post/PostContent/PostContent.module.scss
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/components/Post/PostList/PostList.module.scss
  src/components/Post/PostList/PostListContent.tsx
  src/components/Post/PostList/index.tsx
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/index.tsx
  src/constants/categoryList.ts
  src/pages/index.page.tsx
  src/pages/post/[postId]/index.page.tsx
  src/pages/write/index.page.tsx
  src/utils/getElaspedTime.ts
  src/utils/getKeyByValue.ts
Labels: 💄design, ✨ feat

#128 [Feature] 포스트 이미지 상세보기 기능 및 댓글 컴포넌트 리팩토링
  .eslintrc.json
  icon.svg
  src/components/Common/CommentCard/CommentCard.module.scss
  src/components/Common/CommentInput/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Input/Input.module.scss
  src/components/Common/Input/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/Toast/Toast.module.scss
  src/components/Common/Toast/index.tsx
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/mockData.ts
  src/components/Post/Markdown/Markdown.module.scss
  src/components/Post/Markdown/index.tsx
  src/components/Post/PostComment/PostComment.module.scss
  src/pages/post/[postId]/mockData.ts
  src/pages/write/index.page.tsx
  src/styles/globals.scss
Labels: ♻️refactor, ✨ feat

#129 [feat] 검색 화면 무한스크롤 적용 / 알림 실시간 확인 적용
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
  src/components/Common/TodayQuestion/index.tsx
  src/components/Common/TodayQuestion/type.ts
  src/components/Search/SearchAuthorProfileList/index.tsx
  src/components/Search/SearchList/index.tsx
Labels: ✨ feat

#130 [fix] 피드 업로드 오류 해결
  server.js
  src/api/fetchData.ts
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/api.ts
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/CreateFeed/type.ts
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedList/FeedList.module.scss
Labels: 🐛 bug

#138 [Feature] 이모지 클릭 방법 및 UI 수정
  src/components/Common/ContentContainer/index.tsx
  src/components/Common/EmojiBundle/EmojiBundle.module.scss
  src/components/Common/EmojiBundle/index.tsx
  src/components/Common/EmojiButton/EmojiButton.module.scss
  src/components/Common/EmojiButton/index.tsx
  src/components/Common/EmojiSelection/EmojiSelection.module.scss
  src/components/Common/EmojiSelection/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/NavigationBar/index.tsx
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/ReactionContainer/index.tsx
  src/components/Common/SearchInput/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Post/Markdown/index.tsx
  src/components/Post/MarkdownEditor/customPreviewButton.module.scss
  src/components/Post/MarkdownEditor/customPreviewButton.tsx
  src/components/Post/MarkdownEditor/index.tsx
  src/components/Post/PostContent/PostContent.module.scss
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostPreview/PostPreview.module.scss
  src/components/Post/PostPreview/index.tsx
  src/components/Profile/AuthForm/index.tsx
  src/hooks/useSendEmojiRequest.ts
  src/pages/index.page.tsx
  src/pages/post/[postId]/index.page.tsx
  src/styles/globals.scss
Labels: 💄design, ♻️refactor, ✨ feat

#142 [Feat] 해시태그 및 제목 글자 수 제한, 빌드오류 수정
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/Markdown/index.tsx
  src/components/Post/MarkdownEditor/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/hooks/useToast.ts
Labels: 🐛 bug, ✨ feat

#141 [Feat] 피드 생성하기
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/FeedCard/index.tsx
Labels: 🐛 bug, ✨ feat

#145 [Feat] 프로필 페이지 인증 안된 페이지 / 프로필 이미지 삭제 등
  public/images/dropdown.svg
  public/images/logout.svg
  src/@types/type.ts
  src/components/Common/Buttons/SortDropdown/SortDropdown.module.scss
  src/components/Common/ContentContainer/index.tsx
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ImageInput/RenderImageLabel/index.tsx
  src/components/Common/ImageInput/index.tsx
  src/components/Common/ProfilePopOver/ProfileDropdown.module.scss
  src/components/Common/ProfilePopOver/index.tsx
  src/components/Profile/ProfileContent/EmptyContent.module.scss
  src/components/Profile/ProfileContent/EmptyContent.tsx
  src/components/Profile/ProfileContent/ProfileContent.tsx
  src/components/Profile/ProfileEditModal/ProfileEditModal.module.scss
  src/components/Profile/ProfileEditModal/getImageUploadUrl.ts
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileEditModal/uploadImageToS3.ts
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/index.tsx
  src/hooks/useFollowClick.ts
  src/pages/profile/api.ts
  src/pages/profile/index.page.tsx
  src/pages/profile/setSSRtoReactQuery.tsx
  src/pages/profile/types.ts
  src/utils/onErrorImage.ts
Labels: 🐛 bug, 💄design, ✨ feat

#149 [Feat] 알림 타입 대응, 알림 피드, 팝오버 뜨는곳 모든 곳에 비로그인시 로그인 모달 대체, 모달 관련 보완점 추가
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/Layout/Notification/type.ts
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
  src/components/Search/api.ts
  src/pages/profile/setSSRtoReactQuery.tsx
  src/styles/globals.scss
Labels: ✨ feat

#152 [Refactor] QA 반영 및 리팩토링
  src/components/Common/CommentCard/CommentCard.module.scss
  src/components/Common/CommentCard/EditComment.module.scss
  src/components/Common/CommentCard/EditComment.tsx
  src/components/Common/CommentCard/index.tsx
  src/components/Common/CommentInput/index.tsx
  src/components/Common/EmojiBundle/EmojiBundle.module.scss
  src/components/Common/EmojiBundle/index.tsx
  src/components/Common/EmojiSelection/EmojiSelection.module.scss
  src/components/Common/EmojiSelection/index.tsx
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/Input/Textarea.module.scss
  src/components/Common/Input/Textarea.tsx
  src/components/Common/WriterProfile/index.tsx
  src/components/Post/MarkdownEditor/handleUploadImage.ts
  src/components/Post/PostList/PostList.module.scss
Labels: 💄design, ✨ feat

#151 [Fix] 모달 스크롤 버그 수정, 디자인 검수대로 스타일 변경
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/SearchInput/SearchInput.module.scss
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
Labels: 🐛 bug, 💄design

#155 [Feat] 피드 댓글 리패치, 피드 댓글 무한스크롤
  src/components/Common/CommentInput/CommentInput.module.scss
  src/components/Common/CommentInput/index.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/components/Post/PostComment/PostComment.module.scss
  src/components/Post/PostComment/index.tsx
  src/hooks/useCommentRequest.ts
Labels: 🐛 bug, ♻️refactor

#157 [Feat] 댓글 수정, 삭제 리패치, 피드 생성 리로드 처리, 피드 삭제 리로드 처리
  src/@types/type.ts
  src/components/Common/CommentCard/index.tsx
  src/components/Common/CommentInput/index.tsx
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Feed/CreateFeed/api.ts
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/EditFeed/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/api.ts
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/components/Post/PostComment/index.tsx
  src/hooks/useCommentRequest.ts
  src/hooks/useCreateFeedRequest.ts
  src/hooks/useRefetchFeed.ts
  src/styles/export.module.scss
Labels: 🐛 bug, ♻️refactor

#158 [Feat] QA 수정사항 반영 및 타입 오류 수정
  src/components/Profile/MyFeedList/index.tsx
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/ProfileContent/ProfileContent.tsx
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileHeader/index.tsx
  src/pages/profile/index.page.tsx
Labels: 🐛 bug, ✨ feat

#160 [Refactor] favicon 세팅 및 아이콘 색상 변경
  public/favicon.ico
  src/components/Common/IconCollection/index.tsx
  src/components/Profile/FollowList/Follow/index.tsx
  src/components/Search/SearchAuthorProfile/index.tsx
  src/pages/_app.page.tsx
Labels: ♻️refactor

#159 [Fix] 알림 피드인경우 모달이 안열림 & 라우팅 이상함 문제 해결
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
Labels: 🐛 bug

#164 [Fix] 알림 미인증 사용자 토스트 처리 추가
  src/components/Common/Layout/Notification/index.tsx
Labels: 🐛 bug

#165 [Feat] 알림목록에서 팔로우 버튼 제거 및 멤버 상태(비로그인, 미인증, 인증) 확인 훅 생성
  public/images/profile.svg
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/DeleteModal/index.tsx
  src/components/Common/EmojiBundle/index.tsx
  src/components/Common/EmojiButton/index.tsx
  src/components/Common/EmojiSelection/EmojiSelection.module.scss
  src/components/Common/EmojiSelection/index.tsx
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Layout/Notification/Notification.module.scss
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/Layout/Notification/type.ts
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/SearchInput/index.tsx
  src/components/Common/TextWithLinks/TextWithLinks.module.scss
  src/components/Common/TextWithLinks/index.tsx
  src/components/Common/Toast/index.tsx
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedList/index.tsx
  src/components/Post/Markdown/CodeBlock.tsx
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostList/PostList.module.scss
  src/components/Post/PostPreview/index.tsx
  src/components/Profile/ProfileContent/EmptyContent.module.scss
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Search/SearchList/index.tsx
  src/hooks/useFetchMemberStatus.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useOpenLoginModal.ts
  src/styles/globals.scss
Labels: 💄design, ♻️refactor, ✨ feat

#169 [Feat] 프로필 팝오버 수정 등 완성
  public/images/certification.svg
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ProfilePopOver/ProfileDropdown.module.scss
  src/components/Common/ProfilePopOver/index.tsx
  src/components/Profile/MyPostList/MyPostList.module.scss
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/ProfileContent/EmptyContent.module.scss
  src/components/Profile/ProfileEditModal/ProfilePopOver/ProfilePopOver.module.scss
  src/components/Profile/ProfileEditModal/ProfilePopOver/index.tsx
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/index.tsx
  src/pages/_app.page.tsx
  src/pages/profile/MemberDataContainer.module.scss
  src/pages/profile/index.page.tsx
Labels: 🐛 bug, 💄design, ✨ feat

#170 [Design] 프로필 페이지 디자인 수정
  .eslintrc.json
  src/components/Common/IconCollection/index.tsx
  src/components/Profile/MyPostList/MyPostList.module.scss
  src/components/Profile/ProfileContent/EmptyContent.module.scss
  src/pages/profile/MemberDataContainer.module.scss
  src/pages/profile/index.page.tsx
Labels: 💄design

#172 [Feat] 피드 생성 토스트, 피드 수정 토스트, 피드 댓글 수정 토스트, 피드 댓글 삭제 토스트
  next.config.mjs
  src/api/axios.ts
  src/components/Common/CommentCard/CommentCard.module.scss
  src/components/Common/CommentCard/EditComment.module.scss
  src/components/Common/CommentCard/EditComment.tsx
  src/components/Common/CommentInput/CommentInput.module.scss
  src/components/Common/CommentInput/index.tsx
  src/components/Common/ContentContainer/index.tsx
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Toast/Toast.module.scss
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/EditFeed/EditFeed.module.scss
  src/components/Feed/EditFeed/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/index.tsx
  src/components/Feed/FeedList/FeedList.module.scss
  src/components/Feed/FeedList/index.tsx
  src/hooks/useCommentRequest.ts
  src/hooks/useCreateFeedRequest.ts
  src/hooks/useInfiniteScroll.ts
  src/pages/index.page.tsx
  src/styles/globals.scss
Labels: 🐛 bug, ✨ feat

#173 [Fix] 미인증 프로필 페이지에서 여전히 케밥 대신 버튼 있는 부분 수정
  src/components/Profile/ProfileHeader/index.tsx
Labels: 🐛 bug

#185 [Fix] 다른 사람 프로필로 바뀌는 현상 수정
  src/components/Profile/ProfileEditModal/index.tsx
Labels: 🐛 bug
