Repository project-cosmo-sns/cosmos, pull requests merged in 2024-07, with the labels that each got.

#193 [Feat] 내 프로필에서 스크랩한 목록 불러오기
  src/components/Common/CommentCard/EditComment.tsx
  src/components/Common/CommentCard/index.tsx
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Common/ScrapList/index.tsx
  src/components/Feed/types.ts
  src/components/Post/ScrapButton/index.tsx
  src/components/Profile/MyPostList/MyPostList.module.scss
  src/components/Profile/MyPostList/index.tsx
  src/components/Profile/MyScrapList/api.ts
  src/components/Profile/MyScrapList/index.tsx
  src/components/Profile/ProfileContent/EmptyContent.module.scss
  src/components/Profile/ProfileContent/ProfileContent.tsx
  src/pages/post/[postId]/PostDetail.module.scss
  src/pages/profile/api.ts
  src/pages/profile/index.page.tsx
Labels: ✨ feat

#195 [Feat] authForm ImageInput에 required추가해서 이미지 업로드 안했을 때 막기
  .gitignore
  src/components/Profile/AuthForm/AuthForm.module.scss
  src/components/Profile/AuthForm/index.tsx
Labels: ✨ feat

#200 [Feat] 포스트 목록 사전 렌더링
  src/components/Post/PostList/index.tsx
  src/pages/index.page.tsx
Labels: 🐛 bug

#196 [Deploy] 회원인증 폼 수정사항 반영
  .gitignore
  src/components/Post/PostList/index.tsx
  src/components/Profile/AuthForm/AuthForm.module.scss
  src/components/Profile/AuthForm/index.tsx
  src/pages/index.page.tsx
Labels: ♻️refactor
