Repository project-cosmo-sns/cosmos, pull requests merged in 2024-04, with the labels that each got.

#7 [Feat] 공통 버튼 컴포넌트 제작
  .eslintrc.json
  .github/ISSUE_TEMPLATE/✏️-chore.md
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐛-bug.md
  .github/PULL_REQUEST_TEMPLATE.md
  .prettierrc
  package-lock.json
  package.json
  public/icon/profile.svg
  src/api/axios.ts
  src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
  src/components/Common/Buttons/DefaultButton/DefaultButtonType.ts
  src/components/Common/Buttons/DefaultButton/index.tsx
  src/components/Common/Buttons/FollowButton/FollowButton.module.scss
  src/components/Common/Buttons/FollowButton/FollowButtonType.ts
  src/components/Common/Buttons/FollowButton/index.tsx
  src/components/Common/Buttons/NoticeButton/NoticeButton.module.scss
  src/components/Common/Buttons/NoticeButton/NoticeButtonType.ts
  src/components/Common/Buttons/NoticeButton/index.tsx
  src/components/Common/Buttons/SortDropdown/SortDropdown.module.scss
  src/components/Common/Buttons/SortDropdown/SortDropdownType.ts
  src/components/Common/Buttons/SortDropdown/index.tsx
  src/components/Profile/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader.tsx
  src/pages/profile/index.page.tsx
  src/styles/_variables.scss
  src/styles/globals.scss
  src/utils/Cookies.ts
  src/utils/QueryProvider.tsx
Labels: 💄design, ✨ feat

#9 [Feature] navbar, sidebar 제작
  public/icon/purple.svg
  src/@types/type.ts
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/Layout/NavigationBar/NavigationBar.module.scss
  src/components/Common/Layout/NavigationBar/index.tsx
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/PopOverBox/index.tsx
  src/hooks/UseOutSideClick.ts
  src/pages/index.page.tsx
Labels: ✨ feat

#14 [Feature] Default 버튼 옵션 추가와 자잘한 수정, 컬러변수 변경
  src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
  src/components/Common/Buttons/DefaultButton/DefaultButtonType.ts
  src/components/Common/Buttons/DefaultButton/index.tsx
  src/components/Common/Buttons/FollowButton/FollowButton.module.scss
  src/components/Common/Buttons/NoticeButton/NoticeButton.module.scss
  src/components/Common/Buttons/SortDropdown/SortDropdown.module.scss
  src/components/Profile/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader.tsx
  src/components/Profile/index.tsx
  src/pages/profile/index.page.tsx
  src/styles/_variables.scss
Labels: 🐛 bug

#13 [Feature] 폰트 설정 추가, 검색 Input 추가, svg관련 컴포넌트 추가
  .eslintrc.json
  public/fonts/Pretendard-Black.woff
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff
  public/fonts/Pretendard-Thin.woff2
  public/images/X.svg
  public/images/add.svg
  public/images/addImage.svg
  public/images/back.svg
  public/images/bell.svg
  public/images/camera.svg
  public/images/check.svg
  public/images/close.svg
  public/images/comment.svg
  public/images/delete.svg
  public/images/doubleLeft.svg
  public/images/doubleRight.svg
  public/images/down.svg
  public/images/edit.svg
  public/images/emoji.svg
  public/images/eye.svg
  public/images/feed.svg
  public/images/followed.svg
  public/images/following.svg
  public/images/glass.svg
  public/images/home.svg
  public/images/kebab.svg
  public/images/left.svg
  public/images/like.svg
  public/images/link.svg
  public/images/logo.svg
  public/images/post.svg
  public/images/profile.svg
  public/images/right.svg
  public/images/scrap.svg
  public/images/setting.svg
  public/images/share.svg
  public/images/up.svg
  public/images/user.svg
  src/components/Common/IconCollection/index.tsx
  src/components/Common/SearchInput/SearchInput.module.scss
  src/components/Common/SearchInput/index.tsx
  src/styles/_fonts.scss
  src/styles/globals.scss
Labels: ✨ feat

#16 [Fix] DefaultButton 상위 선택자 추가(빌드 오류 해결)
  src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
Labels: 🐛 bug

#11 [Feature] 코멘트 인풋, 버튼 UI 제작
  src/components/Common/Buttons/CommentButton/CommentButton.module.scss
  src/components/Common/Buttons/CommentButton/index.tsx
  src/components/Common/CommentInput/CommentInput.module.scss
  src/components/Common/CommentInput/index.tsx
  src/pages/_app.page.tsx
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/styles/globals.scss
Labels: ✨ feat

#24 [Feature] 포스트 상세 (마크다운 제외) 레이아웃 생성
  .eslintrc.json
  src/components/Common/AuthorProfile/AuthorProfile.module.scss
  src/components/Common/AuthorProfile/index.tsx
  src/components/Common/CommentCard/CommentCard.module.scss
  src/components/Common/CommentCard/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ReactionContainer/ReactionContainer.module.scss
  src/components/Common/ReactionContainer/index.tsx
  src/components/Post/HashTag/HashTag.module.scss
  src/components/Post/HashTag/index.tsx
  src/pages/post/[id]/PostDetail.module.scss
  src/pages/post/[id]/index.page.tsx
  src/pages/post/[id]/mockData.ts
Labels: ✨ feat

#22 [Feautre] layout, 이미지 인풋 구현
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/ImageInput/ImageInput.module.scss
  src/components/Common/ImageInput/RenderImageLabel/index.tsx
  src/components/Common/ImageInput/index.tsx
  src/components/Common/Layout/Layout.module.scss
  src/components/Common/Layout/NavigationBar/NavigationBar.module.scss
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/Layout/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/PopOverBox/index.tsx
  src/components/Common/Toast/Toast.module.scss
  src/components/Common/Toast/index.tsx
  src/pages/_app.page.tsx
Labels: ✨ feat

#29 [feature] 알림 컴포넌트 추가
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/Layout/Notification/Notification.module.scss
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationItem/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/PopOverBox/index.tsx
  src/hooks/useOutSideClick.ts
Labels: ✨ feat

#31 [Feature] follow 모달 제작
  src/components/Common/Buttons/FollowButton/FollowButton.module.scss
  src/components/Common/Buttons/FollowButton/FollowButtonType.ts
  src/components/Common/Buttons/FollowButton/index.tsx
  src/components/Common/GenerationBadge/Generation.module.scss
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/Toast/Toast.module.scss
  src/components/Common/Toast/index.tsx
  src/components/Profile/FollowList/Follow/Follow.module.scss
  src/components/Profile/FollowList/Follow/index.tsx
  src/components/Profile/FollowList/FollowList.module.scss
  src/components/Profile/FollowList/FollowMockData.ts
  src/components/Profile/FollowList/index.tsx
  src/pages/404/ErrorPage.module.scss
  src/pages/404/index.page.jsx
  src/pages/_app.page.tsx
  src/pages/test/index.page.tsx
Labels: ✨ feat

#33 [Featrue] 피드 관련 ui 제작
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/Badge/TermBadge/TermBadge.module.scss
  src/components/Common/Badge/TermBadge/index.tsx
  src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
  src/components/Common/CommentInput/CommentInput.module.scss
  src/components/Common/Layout/Layout.module.scss
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedCardList/FeedCardList.module.scss
  src/components/Feed/FeedCardList/index.tsx
  src/components/Feed/FeedCardList/mockData.js
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/index.tsx
  src/components/Profile/FollowList/index.tsx
  src/hooks/useOutSideClick.ts
  src/pages/test/index.page.tsx
  src/pages/test/modalTest.page.tsx
Labels: ✨ feat

#30 [Feature] 프로필 페이지 UI 완성
  src/components/Common/Buttons/DefaultButton/DefaultButton.module.scss
  src/components/Common/ClassBadge/ClassBadge.module.scss
  src/components/Common/ClassBadge/index.tsx
  src/components/Common/GenerationBadge/Generation.module.scss
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Profile/ProfileEditModal/ProfileEditModal.module.scss
  src/components/Profile/ProfileEditModal/index.tsx
  src/components/Profile/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/.gitkeep
  src/components/Profile/ProfileHeader/ProfileHeader.module.scss
  src/components/Profile/ProfileHeader/index.tsx
  src/components/Profile/index.tsx
  src/pages/profile/index.page.tsx
  src/pages/profile/mockData.ts
  src/pages/test/modalTest.page.tsx
  src/styles/_mixins.scss
Labels: 💄design, ✨ feat

#35 [feat] 알림 모달 추가, 토글 버튼 추가
  src/components/Common/Buttons/ToggleButton/ToggleButton.module.scss
  src/components/Common/Buttons/ToggleButton/index.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss
  src/components/Common/Layout/Notification/NotificationModal/index.tsx
  src/components/Common/Layout/Notification/index.tsx
Labels: ✨ feat

#34 [Feature] 로그인 모달 / 회원인증 모달 제작
  src/@types/type.ts
  src/components/Common/Buttons/LoginButton/LoginButton.module.scss
  src/components/Common/Buttons/LoginButton/index.tsx
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ImageInput/ImageInput.module.scss
  src/components/Common/Layout/NavigationBar/index.tsx
  src/components/Common/LoginModal/LoginModal.module.scss
  src/components/Common/LoginModal/index.tsx
  src/components/Profile/AuthForm/AuthForm.module.scss
  src/components/Profile/AuthForm/index.tsx
  src/components/Profile/FollowList/FollowList.module.scss
  src/components/Profile/FollowList/index.tsx
  src/pages/test/index.page.tsx
Labels: ✨ feat

#38 [design] 알림 관련 반응형 대응
  src/components/Common/Layout/Notification/Notification.module.scss
  src/components/Common/Layout/Notification/NotificationItem/NotificationItem.module.scss
  src/components/Common/Layout/Notification/NotificationModal/NotificationModal.module.scss
  src/components/Common/Layout/Notification/NotificationModal/index.tsx
  src/components/Common/Layout/Notification/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/styles/globals.scss
Labels: 💄design

#43 [Fix] FeedCard 관련 scss 수정 modal css 수정
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/CommentCard/index.tsx
  src/components/Common/Layout/Modal/Modal.module.scss
  src/components/Common/Layout/Modal/index.tsx
  src/components/Common/Layout/Notification/NotificationModal/index.tsx
  src/components/Common/LoginModal/index.tsx
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedCardList/FeedCardList.module.scss
  src/components/Feed/FeedCardList/index.tsx
  src/components/Feed/FeedDetails/FeedDetails.module.scss
  src/components/Feed/FeedDetails/index.tsx
  src/components/Post/PostContent/index.tsx
  src/components/Profile/AuthForm/index.tsx
  src/components/Profile/FollowList/index.tsx
  src/components/Profile/ProfileEditModal/index.tsx
  src/pages/test/index.page.tsx
  src/pages/test/modalTest.page.tsx
Labels: 💄design

#44 [Fix] reactPortal을 통한 모달 부모요소 조작
  src/components/Common/Layout/Modal/ModalPortal.tsx
  src/components/Common/Layout/Modal/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedCardList/index.tsx
  src/components/Feed/FeedCardList/mockData.js
  src/components/Feed/FeedCardList/mockData.ts
  src/components/Feed/FeedDetails/index.tsx
  src/pages/index.page.tsx
Labels: 🐛 bug

#45 [setting] vercel 배포 브랜치 설정 세팅
  vercel-ignore-step.sh
  vercel.sh
Labels: 📝 docs

#46 [feature] 검색 컨텐츠 추가 / 오늘의 질문 컴포넌트 추가
  src/components/Common/SearchInput/index.tsx
  src/components/Common/TodayQuestion/TodayQuestion.module.scss
  src/components/Common/TodayQuestion/index.tsx
  src/components/Search/SearchAuthorProfile/SearchAuthorProfile.module.scss
  src/components/Search/SearchAuthorProfile/index.tsx
  src/components/Search/SearchAuthorProfileList/SearchAuthorProfileList.module.scss
  src/components/Search/SearchAuthorProfileList/index.tsx
  src/components/Search/SearchList/PostList.module.scss
  src/components/Search/SearchList/index.tsx
  src/pages/index.page.tsx
  src/pages/search/index.page.tsx
Labels: 💄design, ✨ feat

#49 [Feature]auth Form react-hook-form으로 변경
  src/@types/type.ts
  src/components/Common/GenerationBadge/index.tsx
  src/components/Common/ImageInput/RenderImageLabel/index.tsx
  src/components/Common/ImageInput/index.tsx
  src/components/Common/Input/index.tsx
  src/components/Common/LoginModal/LoginModal.module.scss
  src/components/Common/LoginModal/index.tsx
  src/components/Profile/AuthForm/AuthForm.module.scss
  src/components/Profile/AuthForm/index.tsx
  src/components/Profile/FollowList/Follow/Follow.module.scss
  src/components/Profile/FollowList/FollowList.module.scss
  src/components/Profile/FollowList/index.tsx
  src/utils/generationRegex.ts
Labels: ✨ feat

#51 [chore] http locahost -> https변경
  .gitignore
  package.json
  server.js
  src/components/Common/LoginModal/LoginModal.module.scss
  src/components/Common/LoginModal/index.tsx
  src/components/Profile/AuthForm/index.tsx
  src/pages/test/index.page.tsx
  tsconfig.json
Labels: ✨ feat

#53 [Feature] 해시태그 추가 기능
  src/components/Common/ContentContainer/ContentContainer.module.scss
  src/components/Post/HashTag/HashTag.module.scss
  src/components/Post/HashTag/HashTagInput.module.scss
  src/components/Post/HashTag/HashTagInput.tsx
  src/components/Post/HashTag/index.tsx
  src/components/Post/PostContent/index.tsx
  src/components/Post/PostEditor/index.tsx
  src/pages/_app.page.tsx
  src/pages/post/[postId]/mockData.ts
  src/pages/write/index.page.tsx
  src/styles/_variables.scss
Labels: ✨ feat

#54 [Feat] 피드 생성 이미지 업로드 기능 구현
  src/components/Common/Layout/Modal/index.tsx
  src/components/Feed/CreateFeed/CreateFeed.module.scss
  src/components/Feed/CreateFeed/index.tsx
  src/components/Feed/FeedCard/FeedCard.module.scss
  src/components/Feed/FeedCard/index.tsx
  src/components/Feed/FeedCardList/FeedCardList.module.scss
  src/components/Feed/FeedCardList/index.tsx
  src/components/Feed/FeedDetails/index.tsx
Labels: ✨ feat

#58 Feature/login
  package-lock.json
  package.json
  public/images/cosmos.png
  server.js
  src/api/axios.ts
  src/components/Common/AddContentPopOver/AddContentPopOver.module.scss
  src/components/Common/AddContentPopOver/index.tsx
  src/components/Common/Buttons/FollowButton/FollowButton.module.scss
  src/components/Common/Buttons/LoginButton/LoginButton.module.scss
  src/components/Common/IconCollection/index.tsx
  src/components/Common/ImageInput/ImageInput.module.scss
  src/components/Common/Input/Input.module.scss
  src/components/Common/Layout/Layout.module.scss
  src/components/Common/Layout/NavigationBar/NavigationBar.module.scss
  src/components/Common/Layout/SideBar/SideBar.module.scss
  src/components/Common/Layout/SideBar/index.tsx
  src/components/Common/LoginModal/LoginModal.module.scss
  src/components/Common/LoginModal/index.tsx
  src/components/Common/PopOverBox/PopOver.module.scss
  src/components/Common/Toast/Toast.module.scss
  src/components/Profile/AuthForm/AuthForm.module.scss
  src/components/Profile/AuthForm/index.tsx
  src/components/Profile/FollowList/Follow/Follow.module.scss
  src/components/Profile/FollowList/Follow/index.tsx
  src/components/Profile/FollowList/FollowMockData.ts
  src/components/Profile/FollowList/index.tsx
  src/pages/auth/github/index.page.tsx
  src/pages/auth/github/redirect/index.page.tsx
  src/pages/auth/index.page.tsx
  src/pages/index.page.tsx
  src/pages/test/index.page.tsx
  src/styles/Home.module.scss
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/utils/MemberMockData.ts
Labels: ✨ feat
